version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: todoList
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: todoList
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todoList
      SPRING_DATASOURCE_USERNAME: todoList
      SPRING_DATASOURCE_PASSWORD: P@ssw0rd
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

volumes:
  postgres_data:
